# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lightstreams Network
tagline:             'Build tomorrow’s blockchain applications. Today.'
description:         ''
url:                 https://lightstreams.network
baseurl:             ''


# Custom vars
version:             1.0.0
